raise RuntimeError

import colorsys
import re

hexcolor = re.compile(r'#([0-9a-f]{6})', re.MULTILINE | re.IGNORECASE)


def from_match(match):
    c = match[1]
    r = int(c[0:2], base=16)
    g = int(c[2:4], base=16)
    b = int(c[4:6], base=16)
    return r/255, g/255, b/255


def format_color(match, color):
    r, g, b = color
    ro, go, bo = from_match(match)
    dist = abs(r - ro) + abs(g - go) + abs(b - bo)
    if dist < 0.1:
        orig = "not changed"
    else:
        orig = match[0]
    rc = hex(int(r*255))[2:].zfill(2)
    gc = hex(int(g*255))[2:].zfill(2)
    bc = hex(int(b*255))[2:].zfill(2)
    return f"/* {orig} */ #{rc}{gc}{bc}"


def saturate_lightness(match):
    r, g, b = from_match(match)
    h, s, v = colorsys.rgb_to_hsv(r, g, b)
    if s < 0.1:
        color = r, g, b
    else:
        color = colorsys.hsv_to_rgb(h, 1, v)
    return format_color(match, color)


def make_media(match):
    r, g, b = from_match(match)
    h, s, v = colorsys.rgb_to_hsv(r, g, b)
    if s < 0.1:
        r = 1 - r
        g = 1 - g
        b = 1 - b
        color = (r, g, b)
    else:
        v = 1.3 - v
        if v > 1:
            v = 1
        color = colorsys.hsv_to_rgb(h, 1, v)
    return format_color(match, color)


def comment_out(text):
    return '\n'.join([f'/*---- {line.strip().replace("*/", "* /")} ----*/'
                      for line in text.split('\n') if line.strip()])


def process(infile, outfile):
    out = ''
    with open(infile) as file:
        text = file.read()
        saturated = hexcolor.sub(saturate_lightness, text)
        media = hexcolor.sub(make_media, text)
        out = f'''/* auto-generated by saturate.py from {infile} */
/* do not edit this file by hand */
{saturated}
/* ----------- */
@media screen and (prefers-color-scheme: light) {{
{media}
}}
'''

    with open(outfile, 'w') as f:
        f.write(out)


process('pygments_orig.css', 'pygments.css')
process('prism_orig.css', 'prism.css')
print('done')
