name: build site using Pelican
on:
  push:
    branches: [main]
    paths-ignore:
      - static/**
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: pull theme repo
        run: |
          cd pelicantheme
          git fetch --all
          git reset --hard origin/main
          cd ..
      - name: set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.x
      - name: install dependencies
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -r requirements.txt
      - name: clean old outputs
        run: |
          rm -rf drafts/
          rm -rf images/
      - name: build
        run: python3 build.py
      - name: commit changes # copied from ad-m/github-push-action
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "built website" -a
      - name: push built files
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
